PROC IMPORT DATAFILE = 'C:\Users\s206433\SAS\Lesson 3\Vegas.xlsx'
DBMS=XLSX OUT = vegas REPLACE;
RUN;
PROC PRINT DATA = vegas(FIRSTOBS=65 OBS=65);
PROC PRINT DATA = vegas(FIRSTOBS=97 OBS=97);
PROC PRINT DATA = vegas(FIRSTOBS=272 OBS=272);
PROC PRINT DATA = vegas(FIRSTOBS=329 OBS=329);
RUN;
PROC CONTENTS DATA = vegas;
RUN;
